#MUST be 'MOUNT' or 'TELEPORT'
defaultRenderer: "MOUNT"

#Enables demo mode, which will demo the implementation shown on the wiki page.
demoMode: false

#Here are the options for each renderer
options:
    lineHeight: 0.28
    bottomLineHeight: 0.12
    teleport:
        animated: true

#Here you can define overrides for specific entity types to use one or the other. The key must be the name of the entity
#type, found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
typeRenderers:
    ARROW: "TELEPORT"
    DRAGON_FIREBALL: "TELEPORT"
    ENDER_PEARL: "TELEPORT"
    ENDER_SIGNAL: "TELEPORT"
    UNKNOWN: "MOUNT"
    
#Default is to check for update every 24 hours. Time is in seconds.
updateTime: 1440
